name: customStardist
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - charset-normalizer=3.3.0
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - contourpy=1.1.1
  - csbdeep=0.7.4
  - cudatoolkit=11.8.0
  - cudnn=8.1.0.77
  - cycler=0.12.1
  - cytoolz=0.12.2
  - dask-core=2022.12.1
  - enum34=1.1.10
  - fonttools=4.43.1
  - freetype=2.12.1
  - fsspec=2023.9.2
  - idna=3.4
  - imagecodecs-lite=2019.12.3
  - imageio=2.31.1
  - importlib-metadata=6.8.0
  - importlib-resources=6.1.0
  - importlib_resources=6.1.0
  - intel-openmp
  - kiwisolver=1.4.5
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.19
  - libffi=3.4.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libpng=1.6.39
  - libsqlite=3.43.0
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvmlite=0.40.1
  - locket=1.0.0
  - matplotlib-base=3.7.3
  - mkl=2022.1.0
  - munkres=1.1.4
  - networkx=3.1
  - numba=0.57.1
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openssl=3.1.3
  - packaging=23.2
  - partd=1.4.1
  - pathlib=1.0.1
  - pillow=10.0.1
  - pip=23.2.1
  - platformdirs=3.11.0
  - pooch=1.7.0
  - pthread-stubs=0.4
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.8.17
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - requests=2.31.0
  - scikit-image=0.18.1
  - scipy=1.10.1
  - setuptools=68.2.2
  - six=1.16.0
  - stardist=0.8.5
  - tbb=2021.10.0
  - tifffile=2019.7.26.2
  - tk=8.6.13
  - toolz=0.12.0
  - tqdm=4.66.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - unicodedata2=15.1.0
  - urllib3=2.0.6
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - astunparse==1.6.3
      - cachetools==5.3.1
      - flatbuffers==23.5.26
      - gast==0.4.0
      - google-auth==2.23.2
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.59.0
      - h5py==3.9.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==16.0.6
      - markdown==3.5
      - markupsafe==2.1.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==3.19.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - werkzeug==3.0.0
      - wrapt==1.15.0